### PR TITLE
Fix exampleCode to be UUIDv4

### PR DESCRIPTION
**Pull request by m4tonoob**
just make the sample code a uuidv4

### CODE REVIEW

**Comment by m4tonoob** [comment]
very important

**Comment by Ciensprog** [comment]
Hi @m4tonoob ! Ty for your PR I really appreciate it.

FYI, currently example code is following this pattern:
```ts
a  b  c  d  e  f   g  h  i  j  k  l  m  n  o  p
  0  1  2  3  4  5  6  7  8  9  0  1   2  3  4  5
```
That's why currently value is: a0b1c2d3e4f5g6h7i8j9k0l1m2n3o4p5, but I can change this to be UUIDv4.

**Comment by m4tonoob** [comment]
Yeah I saw the pattern, but a uuis is more accurate lol I'm in the mood
today

**Comment by Ciensprog** [comment]
Ohhh no problem, thanks 🍻!

**Pull request merged**
